---
# Source: prometheus-mongodb-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-mongodb-exporter
  labels:
    app.kubernetes.io/name: prometheus-mongodb-exporter
    app.kubernetes.io/instance: prometheus-mongodb-exporter
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-mongodb-exporter-2.7.0
  annotations:
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-mongodb-exporter
      app.kubernetes.io/instance: prometheus-mongodb-exporter
  template:
    metadata:
      annotations:
        checksum/config: 770e1a99a7b6f25ccb7106516ab6279cda389c2ea1a1bfe12c7fbf308525235b
      labels:
        app.kubernetes.io/name: prometheus-mongodb-exporter
        app.kubernetes.io/instance: prometheus-mongodb-exporter
    spec:
      serviceAccountName: prometheus-mongodb-exporter
      containers:
      - name: mongodb-exporter
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: prometheus-mongodb-exporter
                key: mongodb-uri
        image: "ssheehy/mongodb-exporter:0.10.0"
        imagePullPolicy: IfNotPresent
        args:
        - --web.listen-address=:9216
        - --collect.collection
        - --collect.database
        - --collect.indexusage
        - --collect.topmetrics
        - --collect.connpoolstats
        ports:
        - name: metrics
          containerPort: 9216
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 10
        resources:
          {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 10000
          runAsNonRoot: true
          runAsUser: 10000
      affinity:
        {}
      imagePullSecrets:
        []
      nodeSelector:
        {}
      terminationGracePeriodSeconds: 30
      tolerations:
        []
