---
# Source: prometheus-mongodb-exporter/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-mongodb-exporter
  labels:
    app.kubernetes.io/name: prometheus-mongodb-exporter
    app.kubernetes.io/instance: prometheus-mongodb-exporter
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-mongodb-exporter-2.7.0
type: Opaque
data:
  mongodb-uri : ZXhhbXBsZQ==
