---
# Source: prometheus-mongodb-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-mongodb-exporter
  labels:
    app.kubernetes.io/name: prometheus-mongodb-exporter
    app.kubernetes.io/instance: prometheus-mongodb-exporter
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-mongodb-exporter-2.7.0
  annotations:
    {}
spec:
  ports:
    - port: 9216
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: prometheus-mongodb-exporter
    app.kubernetes.io/instance: prometheus-mongodb-exporter
  type: ClusterIP
