---
# Source: prometheus-mongodb-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-mongodb-exporter
  labels:
    app.kubernetes.io/name: prometheus-mongodb-exporter
    app.kubernetes.io/instance: prometheus-mongodb-exporter
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-mongodb-exporter-2.7.0
